version: '3'

tasks:
  install:
    dir: "{{.TASKFILE_DIR}}"
    desc: Perform install
    cmds:
      - ./src/install.sh

  create:
    dir: "{{.TASKFILE_DIR}}"
    desc: Create New Wallpaper
    cmds:
      - docker build . -t quote-wallpaper
      - docker run --user 1000:1000 --mount "type=bind,source={{.TASKFILE_DIR}}/src,target=/src" --mount "type=bind,source={{.TASKFILE_DIR}}/data,target=/data" --mount "type=bind,source={{.TASKFILE_DIR}}/assets,target=/assets" quote-wallpaper

  set:
    desc: Sets wallpaper
    dir: "{{.TASKFILE_DIR}}"
    cmds:
      - ./src/set_wallpaper.sh ./assets/wallpaper.png

