name: Generate Wallpaper
description: Create daily wallpaper
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  make-wallpaper:
    name: "Generate the wallpaper image"
    runs-on: ubuntu-26.04
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v7
      # TODO create-github-app-token to allow pushing around restrictions
      - name: Install requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libmagickwand-dev libclang-dev procps clang pkg-config
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build
      - uses: Swatinem/rust-cache@v2
      - name: create the new wallpaper
        run: cargo run create
      - uses: chainguard-dev/actions/setup-gitsign@main
      - name: push new wallpaper
        env:
          GITSIGN_OIDC_MODE: ambient
        run: |
          git config user.name  'wallpaper-bot[bot]'
          git config user.email 'wallpaper-bot[bot]@users.noreply.github.com'
          git add -f assets/wallpaper.png
          git diff --staged --quiet && exit 0
          git commit -m '[gh-action] Daily Wallpaper'
          git push origin HEAD:main
